sa:
  version: @project.version@
  jwt:
    header: X-Token
    secret: 4f1aaeeb0a76ac6033c5e61d8b5e3e6f
    expire: 604800
  swagger2:
    enabled: true
spring:
  messages:
    encoding: UTF-8
  jpa:
    show-sql: true
    open-in-view: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sa?characterEncoding=utf-8
    username: root
    password: root
  redis:
    database: 1
    host: localhost
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 10000
server:
  port: 8081
logging:
  level:
    root:  info
    org.springframework:  info
    com.github.w4o.ticket:  info
    org.hibernate.type.descriptor.sql.BasicBinder: info